/**
 * Idempotent schema DDL — generated from lib/db/schema.ts via drizzle-kit,
 * transformed to IF NOT EXISTS so it can run safely on every setup attempt.
 * Regenerate after schema changes: npx drizzle-kit generate, then re-transform.
 */
export const SCHEMA_STATEMENTS: string[] = [
  "CREATE TABLE IF NOT EXISTS \"monitoring_run\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"window_key\" text NOT NULL,\n\t\"trigger\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"attempts\" integer DEFAULT 0 NOT NULL,\n\t\"summary\" jsonb,\n\t\"started_at\" text NOT NULL,\n\t\"updated_at\" text NOT NULL,\n\t\"completed_at\" text,\n\t\"last_error\" text\n);",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"monitoring_run_workspace_window_uq\" ON \"monitoring_run\" USING btree (\"workspace_id\",\"window_key\");",
  "CREATE TABLE IF NOT EXISTS \"content_publishing_job\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"suggestion_id\" text NOT NULL,\n\t\"asset_id\" text,\n\t\"idempotency_key\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"exact_payload\" jsonb NOT NULL,\n\t\"provider_response\" jsonb,\n\t\"provider_resource_name\" text,\n\t\"verified_value\" jsonb,\n\t\"attempts\" integer DEFAULT 0 NOT NULL,\n\t\"approved_at\" text NOT NULL,\n\t\"approved_by\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"updated_at\" text NOT NULL,\n\t\"started_at\" text,\n\t\"published_at\" text,\n\t\"failed_at\" text,\n\t\"last_error\" text\n);",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"content_publishing_job_idempotency_uq\" ON \"content_publishing_job\" USING btree (\"idempotency_key\");",
  "CREATE TABLE IF NOT EXISTS \"ai_content_asset\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"suggestion_id\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"mime_type\" text NOT NULL,\n\t\"base64_data\" text NOT NULL,\n\t\"prompt\" text NOT NULL,\n\t\"alt_text\" text NOT NULL,\n\t\"model\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"updated_at\" text NOT NULL\n);",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"ai_content_asset_suggestion_uq\" ON \"ai_content_asset\" USING btree (\"workspace_id\",\"suggestion_id\");",
  "CREATE TABLE IF NOT EXISTS \"app_user\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"role\" text NOT NULL,\n\t\"two_factor_enabled\" boolean NOT NULL,\n\t\"avatar_initials\" text NOT NULL,\n\t\"password_hash\" text,\n\t\"email_verified\" boolean DEFAULT false NOT NULL,\n\t\"google_sub\" text,\n\t\"created_at\" text\n);",
  "CREATE TABLE IF NOT EXISTS \"password_reset_token\" (\n\t\"token_hash\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"expires_at\" text NOT NULL,\n\t\"used_at\" text,\n\t\"created_at\" text NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"audit_log\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"actor\" text NOT NULL,\n\t\"action\" text NOT NULL,\n\t\"target_type\" text NOT NULL,\n\t\"target_id\" text NOT NULL,\n\t\"at\" text NOT NULL,\n\t\"meta\" jsonb,\n\t\"seq\" double precision NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"campaign\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"type\" text NOT NULL,\n\t\"is_automation\" boolean NOT NULL,\n\t\"consent_basis\" text NOT NULL,\n\t\"channel\" text NOT NULL,\n\t\"subject\" text,\n\t\"body\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"scheduled_at\" text,\n\t\"audience_total\" integer NOT NULL,\n\t\"audience_consented\" integer NOT NULL,\n\t\"excluded\" jsonb NOT NULL,\n\t\"stats\" jsonb NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"seq\" double precision NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"customer\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"email\" text,\n\t\"phone\" text,\n\t\"created_at\" text NOT NULL,\n\t\"source\" text NOT NULL,\n\t\"staff_id\" text,\n\t\"visit_count\" integer NOT NULL,\n\t\"last_visit_at\" text,\n\t\"last_request_at\" text,\n\t\"services\" jsonb NOT NULL,\n\t\"sentiment\" text,\n\t\"lifecycle_stage\" text NOT NULL,\n\t\"suppressed_reason\" text,\n\t\"tags\" jsonb NOT NULL,\n\t\"seq\" double precision NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"customer_consent\" (\n\t\"customer_id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"service_consent\" boolean NOT NULL,\n\t\"service_consent_at\" text,\n\t\"marketing_consent\" boolean NOT NULL,\n\t\"marketing_consent_at\" text,\n\t\"consent_channel\" text NOT NULL,\n\t\"consent_source_text\" text NOT NULL,\n\t\"casl_captured\" boolean NOT NULL,\n\t\"withdrawn_at\" text\n);",
  "CREATE TABLE IF NOT EXISTS \"dataset_meta\" (\n\t\"workspace_id\" text PRIMARY KEY NOT NULL,\n\t\"metrics\" jsonb NOT NULL,\n\t\"competitors\" jsonb NOT NULL,\n\t\"aeo\" jsonb NOT NULL,\n\t\"rank_scans\" jsonb NOT NULL,\n\t\"qr_assets\" jsonb NOT NULL,\n\t\"widgets\" jsonb NOT NULL,\n\t\"milestones\" jsonb NOT NULL,\n\t\"suppression\" jsonb NOT NULL,\n\t\"integrations\" jsonb NOT NULL,\n\t\"feature_flags\" jsonb NOT NULL,\n\t\"invoices\" jsonb NOT NULL,\n\t\"reports\" jsonb NOT NULL,\n\t\"agency\" jsonb NOT NULL,\n\t\"platform\" jsonb NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"gbp_task\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"iso_week\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"title\" text NOT NULL,\n\t\"rationale\" text NOT NULL,\n\t\"preview\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"impact\" text NOT NULL,\n\t\"effort_mins\" integer NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"seq\" double precision NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"location\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"category\" text NOT NULL,\n\t\"vertical\" text NOT NULL,\n\t\"address\" text NOT NULL,\n\t\"city\" text NOT NULL,\n\t\"region\" text NOT NULL,\n\t\"timezone\" text NOT NULL,\n\t\"google_place_id\" text,\n\t\"review_url\" text NOT NULL,\n\t\"rating\" double precision NOT NULL,\n\t\"review_count\" integer NOT NULL,\n\t\"joined_at\" text NOT NULL,\n\t\"gbp_connected\" boolean NOT NULL,\n\t\"profile_description\" text NOT NULL,\n\t\"profile_primary_category\" text NOT NULL,\n\t\"profile_secondary_categories\" jsonb NOT NULL,\n\t\"profile_photo_count\" integer NOT NULL,\n\t\"profile_post_count\" integer NOT NULL,\n\t\"profile_qna_count\" integer NOT NULL,\n\t\"profile_hours_set\" boolean NOT NULL,\n\t\"profile_holiday_hours_set\" boolean NOT NULL,\n\t\"profile_services_with_descriptions\" integer NOT NULL,\n\t\"profile_services_total\" integer NOT NULL,\n\t\"profile_response_rate\" double precision NOT NULL,\n\t\"profile_completeness\" double precision NOT NULL,\n\t\"gbp_snapshot\" jsonb,\n\t\"gbp_audit\" jsonb,\n\t\"suggestion_inbox\" jsonb\n);",
  "CREATE TABLE IF NOT EXISTS \"notification\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"title\" text NOT NULL,\n\t\"body\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"read\" boolean NOT NULL,\n\t\"seq\" double precision NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"organization\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"legal_name\" text NOT NULL,\n\t\"region\" text NOT NULL,\n\t\"org_type\" text NOT NULL,\n\t\"billing_email\" text NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"private_feedback\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"customer_name\" text NOT NULL,\n\t\"rating\" integer NOT NULL,\n\t\"text\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"resolved\" boolean NOT NULL,\n\t\"seq\" double precision NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"qr_asset\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"scope\" text NOT NULL,\n\t\"staff_id\" text,\n\t\"label\" text NOT NULL,\n\t\"slug\" text NOT NULL,\n\t\"target_url\" text NOT NULL,\n\t\"scans\" integer DEFAULT 0 NOT NULL,\n\t\"page_opens\" integer DEFAULT 0 NOT NULL,\n\t\"degraded\" boolean DEFAULT false NOT NULL,\n\t\"seq\" integer\n);",
  "CREATE TABLE IF NOT EXISTS \"review\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"author\" text NOT NULL,\n\t\"rating\" integer NOT NULL,\n\t\"text\" text NOT NULL,\n\t\"published_at\" text NOT NULL,\n\t\"source\" text NOT NULL,\n\t\"durability\" text NOT NULL,\n\t\"vanished_at\" text,\n\t\"matched_request_id\" text,\n\t\"match_confidence\" double precision,\n\t\"needs_reply\" boolean NOT NULL,\n\t\"seq\" double precision NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"review_draft\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text,\n\t\"request_id\" text,\n\t\"review_id\" text,\n\t\"kind\" text NOT NULL,\n\t\"variants\" jsonb NOT NULL,\n\t\"approved_variant_index\" integer,\n\t\"generated_by\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"seq\" double precision NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"review_reply\" (\n\t\"review_id\" text PRIMARY KEY NOT NULL,\n\t\"id\" text NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"text\" text NOT NULL,\n\t\"tone\" text NOT NULL,\n\t\"source\" text NOT NULL,\n\t\"posted_at\" text NOT NULL,\n\t\"approved_by\" text NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"review_request\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"customer_id\" text NOT NULL,\n\t\"customer_name\" text NOT NULL,\n\t\"staff_id\" text,\n\t\"channel\" text NOT NULL,\n\t\"token\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"is_test\" boolean NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"sent_at\" text,\n\t\"opened_at\" text,\n\t\"clicked_at\" text,\n\t\"rating\" integer,\n\t\"attributes\" jsonb NOT NULL,\n\t\"private_feedback\" text,\n\t\"suppressed_reason\" text,\n\t\"seq\" double precision NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"staff_invite\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"role\" text NOT NULL,\n\t\"token\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"seq\" double precision NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"staff_member\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"display_name\" text NOT NULL,\n\t\"role\" text NOT NULL,\n\t\"qr_token\" text NOT NULL,\n\t\"active\" boolean NOT NULL,\n\t\"streak_days\" integer NOT NULL,\n\t\"captures\" integer NOT NULL,\n\t\"detected_reviews\" integer NOT NULL,\n\t\"last_active_at\" text,\n\t\"avatar_initials\" text NOT NULL,\n\t\"seq\" double precision NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"subscription\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"tier\" text NOT NULL,\n\t\"interval\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"trial_ends_at\" text,\n\t\"currency\" text NOT NULL,\n\t\"stripe_customer_id\" text,\n\t\"stripe_subscription_id\" text,\n\t\"stripe_price_id\" text,\n\t\"current_period_end\" text,\n\t\"cancel_at_period_end\" boolean,\n\t\"usage\" jsonb NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"workspace\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"organization_id\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"vertical\" text NOT NULL,\n\t\"region\" text NOT NULL,\n\t\"timezone\" text NOT NULL,\n\t\"plan\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"white_label\" jsonb,\n\t\"industry_config\" jsonb,\n\t\"settings\" jsonb,\n\t\"is_demo\" boolean DEFAULT false NOT NULL,\n\t\"referred_by_workspace_id\" text,\n\t\"referral_reward_status\" text,\n\t\"referral_reward_applied_at\" text\n);",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"qr_asset_slug_uq\" ON \"qr_asset\" USING btree (\"slug\");",
  "CREATE TABLE IF NOT EXISTS \"google_credential\" (\n\t\"workspace_id\" text PRIMARY KEY NOT NULL,\n\t\"encrypted_refresh_token\" text NOT NULL,\n\t\"google_account\" text,\n\t\"scopes\" text NOT NULL,\n\t\"connected_at\" text NOT NULL,\n\t\"updated_at\" text NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"instagram_credential\" (\n\t\"workspace_id\" text PRIMARY KEY NOT NULL,\n\t\"encrypted_access_token\" text NOT NULL,\n\t\"account_id\" text NOT NULL,\n\t\"username\" text,\n\t\"scopes\" text NOT NULL,\n\t\"expires_at\" text,\n\t\"connected_at\" text NOT NULL,\n\t\"updated_at\" text NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"profile_mutation_job\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"suggestion_id\" text NOT NULL,\n\t\"idempotency_key\" text NOT NULL,\n\t\"target\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"update_mask\" jsonb NOT NULL,\n\t\"before_value\" jsonb,\n\t\"proposed_value\" jsonb NOT NULL,\n\t\"provider_response\" jsonb,\n\t\"verified_value\" jsonb,\n\t\"rollback_value\" jsonb,\n\t\"attempts\" integer DEFAULT 0 NOT NULL,\n\t\"approved_at\" text NOT NULL,\n\t\"approved_by\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"updated_at\" text NOT NULL,\n\t\"started_at\" text,\n\t\"applied_at\" text,\n\t\"failed_at\" text,\n\t\"last_error\" text\n);",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"profile_mutation_job_idempotency_uq\" ON \"profile_mutation_job\" USING btree (\"idempotency_key\");"
];

/**
 * Additive statements that must run even on databases initialized by an earlier
 * schema (the fast-path in ensureSchema() skips the full list once core tables
 * exist). All are IF NOT EXISTS / ADD COLUMN IF NOT EXISTS — safe to run every
 * cold start. New additive migrations go here so existing tenants self-heal.
 */
export const ADDITIVE_STATEMENTS: string[] = [
  "CREATE TABLE IF NOT EXISTS \"monitoring_run\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"window_key\" text NOT NULL,\n\t\"trigger\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"attempts\" integer DEFAULT 0 NOT NULL,\n\t\"summary\" jsonb,\n\t\"started_at\" text NOT NULL,\n\t\"updated_at\" text NOT NULL,\n\t\"completed_at\" text,\n\t\"last_error\" text\n);",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"monitoring_run_workspace_window_uq\" ON \"monitoring_run\" USING btree (\"workspace_id\",\"window_key\");",
  "CREATE TABLE IF NOT EXISTS \"content_publishing_job\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"suggestion_id\" text NOT NULL,\n\t\"asset_id\" text,\n\t\"idempotency_key\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"exact_payload\" jsonb NOT NULL,\n\t\"provider_response\" jsonb,\n\t\"provider_resource_name\" text,\n\t\"verified_value\" jsonb,\n\t\"attempts\" integer DEFAULT 0 NOT NULL,\n\t\"approved_at\" text NOT NULL,\n\t\"approved_by\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"updated_at\" text NOT NULL,\n\t\"started_at\" text,\n\t\"published_at\" text,\n\t\"failed_at\" text,\n\t\"last_error\" text\n);",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"content_publishing_job_idempotency_uq\" ON \"content_publishing_job\" USING btree (\"idempotency_key\");",
  "CREATE TABLE IF NOT EXISTS \"ai_content_asset\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"suggestion_id\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"mime_type\" text NOT NULL,\n\t\"base64_data\" text NOT NULL,\n\t\"prompt\" text NOT NULL,\n\t\"alt_text\" text NOT NULL,\n\t\"model\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"updated_at\" text NOT NULL\n);",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"ai_content_asset_suggestion_uq\" ON \"ai_content_asset\" USING btree (\"workspace_id\",\"suggestion_id\");",
  "CREATE TABLE IF NOT EXISTS \"google_credential\" (\n\t\"workspace_id\" text PRIMARY KEY NOT NULL,\n\t\"encrypted_refresh_token\" text NOT NULL,\n\t\"google_account\" text,\n\t\"scopes\" text NOT NULL,\n\t\"connected_at\" text NOT NULL,\n\t\"updated_at\" text NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"instagram_credential\" (\n\t\"workspace_id\" text PRIMARY KEY NOT NULL,\n\t\"encrypted_access_token\" text NOT NULL,\n\t\"account_id\" text NOT NULL,\n\t\"username\" text,\n\t\"scopes\" text NOT NULL,\n\t\"expires_at\" text,\n\t\"connected_at\" text NOT NULL,\n\t\"updated_at\" text NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS \"password_reset_token\" (\n\t\"token_hash\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"expires_at\" text NOT NULL,\n\t\"used_at\" text,\n\t\"created_at\" text NOT NULL\n);",
  "ALTER TABLE \"app_user\" ADD COLUMN IF NOT EXISTS \"session_version\" integer DEFAULT 0 NOT NULL;",
  // Duplicate-account prevention was application-only, so two concurrent
  // registrations for the same address could both pass the pre-insert check and
  // create two authenticatable accounts. This enforces it in the database.
  //
  // PARTIAL and on lower(email), to match findUserRowByEmail exactly: adding a
  // second location under one organization legitimately inserts another app_user
  // row with the owner's email and NULL credentials, and those rows are excluded
  // from every auth lookup — so they must stay excluded here too.
  "CREATE UNIQUE INDEX IF NOT EXISTS \"app_user_credentialed_email_uq\" ON \"app_user\" (lower(\"email\")) WHERE \"password_hash\" IS NOT NULL OR \"google_sub\" IS NOT NULL;",
  "ALTER TABLE \"subscription\" ADD COLUMN IF NOT EXISTS \"stripe_customer_id\" text;",
  "ALTER TABLE \"subscription\" ADD COLUMN IF NOT EXISTS \"stripe_subscription_id\" text;",
  "ALTER TABLE \"subscription\" ADD COLUMN IF NOT EXISTS \"stripe_price_id\" text;",
  "ALTER TABLE \"subscription\" ADD COLUMN IF NOT EXISTS \"current_period_end\" text;",
  "ALTER TABLE \"subscription\" ADD COLUMN IF NOT EXISTS \"cancel_at_period_end\" boolean;",
  "ALTER TABLE \"workspace\" ADD COLUMN IF NOT EXISTS \"referred_by_workspace_id\" text;",
  "ALTER TABLE \"workspace\" ADD COLUMN IF NOT EXISTS \"referral_reward_status\" text;",
  "ALTER TABLE \"workspace\" ADD COLUMN IF NOT EXISTS \"referral_reward_applied_at\" text;",
  "ALTER TABLE \"location\" ADD COLUMN IF NOT EXISTS \"gbp_snapshot\" jsonb;",
  "ALTER TABLE \"location\" ADD COLUMN IF NOT EXISTS \"gbp_audit\" jsonb;",
  "ALTER TABLE \"location\" ADD COLUMN IF NOT EXISTS \"suggestion_inbox\" jsonb;",
  "CREATE TABLE IF NOT EXISTS \"profile_mutation_job\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"workspace_id\" text NOT NULL,\n\t\"location_id\" text NOT NULL,\n\t\"suggestion_id\" text NOT NULL,\n\t\"idempotency_key\" text NOT NULL,\n\t\"target\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"update_mask\" jsonb NOT NULL,\n\t\"before_value\" jsonb,\n\t\"proposed_value\" jsonb NOT NULL,\n\t\"provider_response\" jsonb,\n\t\"verified_value\" jsonb,\n\t\"rollback_value\" jsonb,\n\t\"attempts\" integer DEFAULT 0 NOT NULL,\n\t\"approved_at\" text NOT NULL,\n\t\"approved_by\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"updated_at\" text NOT NULL,\n\t\"started_at\" text,\n\t\"applied_at\" text,\n\t\"failed_at\" text,\n\t\"last_error\" text\n);",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"profile_mutation_job_idempotency_uq\" ON \"profile_mutation_job\" USING btree (\"idempotency_key\");",
];
